const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const fmt = new Intl.NumberFormat("zh-TW", {maximumFractionDigits: 1});
const titles = {m1:["MODULE 1 · OPERATIONS","異常偵測中心"],m3:["MODULE 3 · ANALYTICS","第一眼分析"],m2:["MODULE 2 · EXPERIMENTATION","實驗營運控制"],m4:["MODULE 4 · PARTNER SUPPORT","夥伴支援助理"]};
let experiments = [];
let chatSession = null;

function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function safe(value){return String(value??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function request(url, options={}){const response=await fetch(url,{cache:"no-store",headers:{"Content-Type":"application/json"},...options});let data;try{data=await response.json()}catch{data={error:"AWS response was not JSON"}}if(!response.ok)throw new Error(data.error||data.message||`HTTP ${response.status}`);return data}

$$('.nav').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.screen;$$('.nav,.screen').forEach(el=>el.classList.remove('active'));button.classList.add('active');$(`#${id}`).classList.add('active');$('#eyebrow').textContent=titles[id][0];$('#page-title').textContent=titles[id][1]}));

$('#run-anomaly').addEventListener('click',async()=>{const button=$('#run-anomaly'),strip=$('.status-strip');button.disabled=true;strip.className='status-strip running';$('#m1-status').textContent='Lambda 執行中 · 正在查詢 Athena 歷史基準…';try{const d=await request('/api/m1/run',{method:'POST',body:'{}'}),a=d.alerts?.[0];if(!a)throw new Error('掃描完成，但沒有偵測到異常');$('#dau-actual').textContent=fmt.format(a.actual);$('#dau-baseline').textContent=fmt.format(a.ewma_baseline);const pct=(a.deviation/a.ewma_baseline)*100;$('#dau-change').textContent=`${pct.toFixed(1)}%`;$('#sigma-value').textContent=`${Math.abs(a.deviation/a.sigma).toFixed(1)}σ deviation`;$('#m1-summary').textContent=`DAU ${a.actual}，低於 EWMA 基準 ${a.ewma_baseline}；偏離已超過 ${a.k_sigma_threshold}σ 告警門檻。`;$('#m1-key').textContent=d.evidence.key;$('#m1-time').textContent=`${d.request.duration_ms} ms · ${new Date(d.request.completed_at).toLocaleTimeString('zh-TW')}`;$('#m1-evidence').classList.remove('hidden');strip.className='status-strip done';$('#m1-status').textContent='AWS 掃描完成 · SNS 告警與 S3 證據已產生';toast('異常已偵測，AWS 證據已寫入')}catch(error){strip.className='status-strip';$('#m1-status').textContent=error.message;toast(error.message)}finally{button.disabled=false}});

function renderReportText(text){const lines=String(text||'').split(/\r?\n/);let html='',inList=false;for(const raw of lines){const line=raw.trim();if(!line)continue;if(line.startsWith('### ')){if(inList){html+='</ul>';inList=false}html+=`<h3>${safe(line.slice(4))}</h3>`}else if(line.startsWith('- ')){if(!inList){html+='<ul>';inList=true}html+=`<li>${safe(line.slice(2))}</li>`}else{if(inList){html+='</ul>';inList=false}html+=`<p>${safe(line)}</p>`}}if(inList)html+='</ul>';return html}
$('#load-report').addEventListener('click',async()=>{const button=$('#load-report');button.disabled=true;button.textContent='讀取中…';try{const d=await request('/api/m3/report');const body=$('#report-body');body.classList.remove('empty');body.innerHTML=renderReportText(d.report_text);$('#report-generated').textContent=`S3 更新 ${new Date(d.evidence.last_modified).toLocaleString('zh-TW')}`;$('#report-key').textContent=d.evidence.key;const metrics=['dau','ggr_usd','deposits_usd'];$('#comparison').innerHTML=metrics.map(key=>{const x=d.comparison[key];return `<div class="comparison-row"><div><strong>${safe(key.toUpperCase())}</strong><small>${fmt.format(x.actual)} vs ${fmt.format(x.baseline_avg_7d)}</small></div><span>${x.pct_change>0?'+':''}${fmt.format(x.pct_change)}%</span></div>`}).join('');toast('已讀取真實 S3 分析報告')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='讀取最新 AWS 報告'}});

function renderExperiments(filter='all'){const rows=filter==='action'?experiments.filter(x=>x.health==='action'):experiments;$('#experiment-rows').innerHTML=rows.slice(0,7).map(x=>`<div class="tr"><span><strong>${safe(x.name)}</strong><small>${safe(x.experiment_id)}</small></span><span>${safe(x.client_site_id)}<small>${safe(x.game_id)}</small></span><span><i class="pill">${safe(x.state)}</i></span><span><i class="pill ${safe(x.health)}">${safe(x.health)}</i><small>${safe(x.health_detail)}</small></span><span>${x.allocation_enabled?'ENABLED':'CONTROL ONLY'}</span><span>${safe(x.srm_status)}<small>n=${safe(x.total_exposed)}</small></span></div>`).join('')||'<div class="tr"><span>沒有符合條件的實驗</span></div>'}
$('#load-experiments').addEventListener('click',loadExperiments);
async function loadExperiments(){const button=$('#load-experiments');button.disabled=true;button.textContent='同步中…';try{const d=await request('/api/m2/experiments');experiments=d.experiments;$('#exp-total').textContent=d.summary.total;$('#exp-running').textContent=d.summary.running;$('#exp-action').textContent=d.summary.needs_action;$('#exp-draft').textContent=d.summary.draft;$('#exp-updated').textContent=`AWS Registry · ${new Date(d.request.completed_at).toLocaleTimeString('zh-TW')}`;renderExperiments($('.filter.active').dataset.filter);toast('Registry 已同步')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='重新整理 Registry'}}
$$('.filter').forEach(button=>button.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderExperiments(button.dataset.filter)}));

function addMessage(role,text,meta='',extra=''){const div=document.createElement('div');div.className=`message ${role} ${extra}`;div.innerHTML=`<p>${safe(text)}</p>${meta?`<small>${safe(meta)}</small>`:''}`;$('#messages').append(div);$('#messages').scrollTop=$('#messages').scrollHeight;return div}
$('#chat-form').addEventListener('submit',async event=>{event.preventDefault();const input=$('#chat-input'),button=$('#chat-form button'),question=input.value.trim();if(!question)return;addMessage('user',question,'Game provider · just now');input.value='';button.disabled=true;const typing=addMessage('assistant','正在查詢受治理的知識範圍…','','typing');try{const d=await request('/api/m4/chat',{method:'POST',body:JSON.stringify({question,session_id:chatSession})});chatSession=d.session_id;typing.remove();addMessage('assistant',d.response,`${d.category} · ${d.request.duration_ms} ms`);$('#chat-proof').textContent=`AWS 回覆 · ${d.request.service} · IAM ${d.request.identity} · ${new Date(d.request.completed_at).toLocaleTimeString('zh-TW')}`;toast('已收到真實 AWS 回覆')}catch(error){typing.remove();addMessage('assistant',`服務暫時無法完成回答：${error.message}`,'AWS request failed','error');toast(error.message)}finally{button.disabled=false;input.focus()}});

fetch('/api/health').then(r=>r.json()).catch(()=>({status:'offline'}));
