const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const fmt = new Intl.NumberFormat("zh-TW", {maximumFractionDigits: 1});
const titles = {m1:["MODULE 1 · OPERATIONS","異常監控中心"],m3:["MODULE 3 · ANALYTICS","第一眼分析"],m2:["MODULE 2 · EXPERIMENTATION","實驗營運控制"],m4:["MODULE 4 · KNOWLEDGE","技術文件助理"]};
let experiments = [];
let chatSession = null;
const recordingMode = new URLSearchParams(window.location.search).has('recording');

const recordingFixtures={
  '/api/m3/report':{comparison:{dau:{actual:91,baseline_avg_7d:205.6,pct_change:-55.7},sessions:{actual:89,baseline_avg_7d:201.1,pct_change:-55.7},new_players:{actual:30,baseline_avg_7d:26.4,pct_change:13.6}},evidence:{key:'gold/first_look_reports/site_b_2026-06-10.json',last_modified:'2026-08-02T01:02:00Z'}},
  '/api/m2/experiments':{summary:{total:6,running:2,needs_action:2,draft:1},experiments:[
    {name:'onboarding-copy-test',experiment_id:'exp_01',client_site_id:'site_a',game_id:'product_01',state:'running',health:'healthy',health_detail:'hourly checks passed',allocation_enabled:true,srm_status:'passed',total_exposed:1240},
    {name:'navigation-layout-test',experiment_id:'exp_02',client_site_id:'site_b',game_id:'product_02',state:'stopped_early',health:'action',health_detail:'hourly guardrail crossed',allocation_enabled:false,srm_status:'passed',total_exposed:684},
    {name:'recommendation-order-test',experiment_id:'exp_03',client_site_id:'site_c',game_id:'product_03',state:'stopped_early',health:'action',health_detail:'sample ratio mismatch',allocation_enabled:false,srm_status:'breached',total_exposed:100},
    {name:'search-ranking-test',experiment_id:'exp_04',client_site_id:'site_a',game_id:'product_04',state:'running',health:'watch',health_detail:'sample building',allocation_enabled:true,srm_status:'insufficient_sample',total_exposed:72},
    {name:'notification-timing-test',experiment_id:'exp_05',client_site_id:'site_b',game_id:'product_05',state:'draft',health:'neutral',health_detail:'not started',allocation_enabled:false,srm_status:'not_checked',total_exposed:'—'},
    {name:'workspace-home-test',experiment_id:'exp_06',client_site_id:'site_c',game_id:'product_06',state:'analyzed',health:'healthy',health_detail:'review ready',allocation_enabled:false,srm_status:'passed',total_exposed:1520}
  ],request:{completed_at:'2026-08-02T01:03:00Z'}},
  '/api/m4/chat':{response:'Verify the X-LEON-Signature header against the exact raw request body using HMAC-SHA256 and your webhook signing secret. Do not parse and re-serialize the payload before verification.',category:'ANSWERABLE',session_id:'recording-session',request:{service:'API Gateway + Lambda + Amazon Bedrock',identity:'integration-partner',duration_ms:642,completed_at:'2026-08-02T01:04:00Z'}}
};

function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function safe(value){return String(value??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function request(url, options={}){if(recordingMode&&recordingFixtures[url])return structuredClone(recordingFixtures[url]);const response=await fetch(url,{cache:"no-store",headers:{"Content-Type":"application/json"},...options});let data;try{data=await response.json()}catch{data={error:"AWS response was not JSON"}}if(!response.ok)throw new Error(data.error||data.message||`HTTP ${response.status}`);return data}

$$('.nav').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.screen;$$('.nav,.screen').forEach(el=>el.classList.remove('active'));button.classList.add('active');const screen=$(`#${id}`);screen.classList.add('active');$('#eyebrow').textContent=titles[id][0];$('#page-title').textContent=titles[id][1];screen.querySelectorAll('.mode-tab').forEach((tab,index)=>tab.classList.toggle('active',index===0));screen.querySelectorAll('.module-mode').forEach((panel,index)=>panel.classList.toggle('active',index===0))}));

$$('.mode-tab').forEach(tab=>tab.addEventListener('click',()=>{const screen=tab.closest('.screen');screen.querySelectorAll('.mode-tab').forEach(x=>x.classList.remove('active'));screen.querySelectorAll('.module-mode').forEach(x=>x.classList.remove('active'));tab.classList.add('active');screen.querySelector(`[data-panel="${tab.dataset.mode}"]`).classList.add('active');if(screen.id==='m1'&&tab.dataset.mode==='interface')requestAnimationFrame(()=>drawHourlyChart(currentMetric))}));

const hourlySeries={
  activeUsers:{title:'每小時活躍使用者',actual:[6,5,10,7,6,2,6,8,10,6],baseline:[9.6,8.7,13,9,10,9.3,9.1,11.3,10.3,10.3],range:3},
  sessions:{title:'每小時工作階段',actual:[6,1,9,2,6,2,5,4,8,3],baseline:[9,7.6,10.6,7.7,7.4,8.1,7.4,9.3,9.4,8.9],range:3},
  interactions:{title:'完成互動數',actual:[23,10,33,14,27,8,23,19,35,21],baseline:[36.9,32,48.6,40.3,31.9,38,30.6,41,40.1,36.7],range:10}
};
const hourlyLabels=['08','09','10','11','12','13','14','15','16','17'];
let currentMetric='activeUsers';
function drawHourlyChart(metricKey){const canvas=$('#hourly-chart');if(!canvas)return;const ctx=canvas.getContext('2d'),series=hourlySeries[metricKey],ratio=window.devicePixelRatio||1,w=canvas.clientWidth||920,h=canvas.clientHeight||255;canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);const pad={l:43,r:18,t:18,b:34},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;const values=[...series.actual,...series.baseline.map(x=>x+series.range)];const max=Math.ceil(Math.max(...values)*1.1/10)*10;const x=i=>pad.l+(cw*i/(hourlyLabels.length-1)),y=v=>pad.t+ch-(v/max*ch);ctx.font='11px Segoe UI';ctx.fillStyle='#7189a3';ctx.strokeStyle='#1d3851';ctx.lineWidth=1;for(let i=0;i<=4;i++){const gy=pad.t+ch*i/4;ctx.beginPath();ctx.moveTo(pad.l,gy);ctx.lineTo(w-pad.r,gy);ctx.stroke();ctx.fillText(Math.round(max*(1-i/4)),5,gy+4)}hourlyLabels.forEach((label,i)=>ctx.fillText(`${label}:00`,x(i)-14,h-9));ctx.fillStyle='rgba(61,214,198,.10)';ctx.beginPath();series.baseline.forEach((v,i)=>{const py=y(v+series.range);i?ctx.lineTo(x(i),py):ctx.moveTo(x(i),py)});[...series.baseline].reverse().forEach((v,ri)=>{const i=series.baseline.length-1-ri;ctx.lineTo(x(i),y(Math.max(0,v-series.range)))});ctx.closePath();ctx.fill();function line(values,color,dash=[]){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.setLineDash(dash);values.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();ctx.setLineDash([])}line(series.baseline,'#7994ad',[6,6]);line(series.actual,'#3dd6c6');const anomalyIndex=5;ctx.fillStyle='#ff6b72';ctx.shadowColor='#ff6b72';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x(anomalyIndex),y(series.actual[anomalyIndex]),6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#ff9ba0';ctx.font='700 11px Segoe UI';ctx.fillText('異常',x(anomalyIndex)-13,y(series.actual[anomalyIndex])-13)}
$$('.metric-choice').forEach(button=>button.addEventListener('click',()=>{currentMetric=button.dataset.metric;$$('.metric-choice').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#chart-title').textContent=hourlySeries[currentMetric].title;drawHourlyChart(currentMetric)}));
window.addEventListener('resize',()=>{if($('#m1').classList.contains('active')&&$('#m1 [data-panel="interface"]').classList.contains('active'))drawHourlyChart(currentMetric)});

const neutralMetrics={dau:'ACTIVE USERS',sessions:'SESSIONS',new_players:'NEW USERS'};
function renderNeutralReport(data){const rows=Object.entries(neutralMetrics).filter(([key])=>data.comparison?.[key]).map(([key,label])=>{const x=data.comparison[key];return `<li><strong>${label}</strong>：${fmt.format(x.actual)}，七日基準 ${fmt.format(x.baseline_avg_7d)}（${x.pct_change>0?'+':''}${fmt.format(x.pct_change)}%）</li>`}).join('');return `<h3>Site-level usage first look</h3><p>系統已將本次異常與前七日基準完成比較，以下僅呈現中性的使用與互動指標。</p><h3>Observed movement</h3><ul>${rows}</ul><h3>Interpretation boundary</h3><p>這是需要調查的營運訊號，不代表系統已判定根因；後續處置仍由負責人依發布紀錄與產品脈絡決定。</p>`}
$('#load-report').addEventListener('click',async()=>{const button=$('#load-report');button.disabled=true;button.textContent='讀取中…';try{const d=await request('/api/m3/report');const body=$('#report-body');body.classList.remove('empty');body.innerHTML=renderNeutralReport(d);$('#report-generated').textContent=`S3 更新 ${new Date(d.evidence.last_modified).toLocaleString('zh-TW')}`;$('#report-key').textContent=d.evidence.key;$('#comparison').innerHTML=Object.entries(neutralMetrics).filter(([key])=>d.comparison?.[key]).map(([key,label])=>{const x=d.comparison[key];return `<div class="comparison-row"><div><strong>${label}</strong><small>${fmt.format(x.actual)} vs ${fmt.format(x.baseline_avg_7d)}</small></div><span>${x.pct_change>0?'+':''}${fmt.format(x.pct_change)}%</span></div>`}).join('');toast('已讀取真實 S3 分析報告')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='讀取最新 AWS 報告'}});

function neutralLabel(value){return String(value??'—').replace(/game/gi,'product').replace(/player/gi,'user').replace(/payout/gi,'experience').replace(/ggr/gi,'quality metric').replace(/bet/gi,'interaction')}
function renderExperiments(filter='all'){const rows=filter==='action'?experiments.filter(x=>x.health==='action'):experiments;$('#experiment-rows').innerHTML=rows.slice(0,7).map(x=>`<div class="tr"><span><strong>${safe(neutralLabel(x.name))}</strong><small>${safe(x.experiment_id)}</small></span><span>${safe(x.client_site_id)}<small>${safe(neutralLabel(x.game_id))}</small></span><span><i class="pill">${safe(x.state)}</i></span><span><i class="pill ${safe(x.health)}">${safe(x.health)}</i><small>${safe(neutralLabel(x.health_detail))}</small></span><span>${x.allocation_enabled?'ENABLED':'CONTROL ONLY'}</span><span>${safe(x.srm_status)}<small>n=${safe(x.total_exposed)}</small></span></div>`).join('')||'<div class="tr"><span>沒有符合條件的實驗</span></div>'}
$('#load-experiments').addEventListener('click',loadExperiments);
async function loadExperiments(){const button=$('#load-experiments');button.disabled=true;button.textContent='同步中…';try{const d=await request('/api/m2/experiments');experiments=d.experiments;$('#exp-total').textContent=d.summary.total;$('#exp-running').textContent=d.summary.running;$('#exp-action').textContent=d.summary.needs_action;$('#exp-draft').textContent=d.summary.draft;$('#exp-updated').textContent=`AWS Registry · ${new Date(d.request.completed_at).toLocaleTimeString('zh-TW')}`;renderExperiments($('.filter.active').dataset.filter);toast('Registry 已同步')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='重新整理 Registry'}}
$$('.filter').forEach(button=>button.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderExperiments(button.dataset.filter)}));

function addMessage(role,text,meta='',extra=''){const div=document.createElement('div');div.className=`message ${role} ${extra}`;div.innerHTML=`<p>${safe(text)}</p>${meta?`<small>${safe(meta)}</small>`:''}`;$('#messages').append(div);$('#messages').scrollTop=$('#messages').scrollHeight;return div}
$('#chat-form').addEventListener('submit',async event=>{event.preventDefault();const input=$('#chat-input'),button=$('#chat-form button'),question=input.value.trim();if(!question)return;addMessage('user',question,'Integration partner · just now');input.value='';button.disabled=true;const typing=addMessage('assistant','正在查詢受治理的知識範圍…','','typing');try{const d=await request('/api/m4/chat',{method:'POST',body:JSON.stringify({question,session_id:chatSession})});chatSession=d.session_id;typing.remove();addMessage('assistant',d.response,`${d.category} · ${d.request.duration_ms} ms`);$('#chat-proof').textContent=`AWS 回覆 · ${d.request.service} · IAM ${d.request.identity} · ${new Date(d.request.completed_at).toLocaleTimeString('zh-TW')}`;toast('已收到真實 AWS 回覆')}catch(error){typing.remove();addMessage('assistant',`服務暫時無法完成回答：${error.message}`,'AWS request failed','error');toast(error.message)}finally{button.disabled=false;input.focus()}});

if(!recordingMode)fetch('/api/health').then(r=>r.json()).catch(()=>({status:'offline'}));
